spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    web-application-type: none
  flyway:
    enabled: false
    check-location: false
    baselineOnMigrate: true
  datasource:
    url: 'jdbc:h2:mem:matchbox;DB_CLOSE_DELAY=-1'
    driverClassName: org.h2.Driver

    # database connection pool size
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.hbm2ddl.auto: create
      ###    These settings will enable fulltext search with lucene
      hibernate.search.enabled: true
  batch:
    job:
      enabled: false
